apiVersion: resource.atlassian.com/v1
kind: Compute
description: "Sample compute"
metadata:
  name: compute-example-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-deploy-test
      version: "1.0"
  template:
    metadata:
      labels:
        app: k8s-deploy-test
        version: "1.0"
    spec:
      containers:
      - name: tea
        image: nginxdemos/hello
        ports:
        - containerPort: 80