apiVersion: smith.atlassian.com/v1
kind: Bundle
metadata:
  name: compute-graph
spec:
  resources:
  - name: compute-v-1
    dependsOn:
      - compute-v-3
    spec:
      apiVersion: resource.atlassian.com/v1
      kind: Compute
      description: "Sample compute controlled by Smith"
      metadata:
        name: compute-v-1
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: k8s-deploy-test
            version: "1.0"
        template:
          metadata:
            labels:
              app: k8s-deploy-test
              version: "1.0"
          spec:
            containers:
            - name: tea
              image: nginxdemos/hello
              ports:
              - containerPort: 80
  - name: compute-v-2
    spec:
      apiVersion: resource.atlassian.com/v1
      kind: Compute
      description: "Sample compute controlled by Smith"
      metadata:
        name: compute-v-2
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: k8s-deploy-test
            version: "1.0"
        template:
          metadata:
            labels:
              app: k8s-deploy-test
              version: "1.0"
          spec:
            containers:
            - name: tea
              image: nginxdemos/hello
              ports:
              - containerPort: 80
  - name: compute-v-3
    dependsOn:
      - compute-v-2
    spec:
      apiVersion: resource.atlassian.com/v1
      kind: Compute
      description: "Sample compute controlled by Smith"
      metadata:
        name: compute-v-3
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: k8s-deploy-test
            version: "1.0"
        template:
          metadata:
            labels:
              app: k8s-deploy-test
              version: "1.0"
          spec:
            containers:
            - name: tea
              image: nginxdemos/hello
              ports:
              - containerPort: 80
  - name: compute-v-4
    dependsOn:
      - compute-v-5
    spec:
      apiVersion: resource.atlassian.com/v1
      kind: Compute
      description: "Sample compute controlled by Smith"
      metadata:
        name: compute-v-4
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: k8s-deploy-test
            version: "1.0"
        template:
          metadata:
            labels:
              app: k8s-deploy-test
              version: "1.0"
          spec:
            containers:
            - name: tea
              image: nginxdemos/hello
              ports:
              - containerPort: 80
  - name: compute-v-5
    spec:
      apiVersion: resource.atlassian.com/v1
      kind: Compute
      description: "Sample compute controlled by Smith"
      metadata:
        name: compute-v-5
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: k8s-deploy-test
            version: "1.0"
        template:
          metadata:
            labels:
              app: k8s-deploy-test
              version: "1.0"
          spec:
            containers:
            - name: tea
              image: nginxdemos/hello
              ports:
              - containerPort: 80                            