apiVersion: smith.atlassian.com/v1
kind: Bundle
metadata:
  name: release-graph
spec:
  resources:
  - name: release-v-1
    dependsOn:
      - release-v-3
    spec:
      apiVersion: deploy.k8s/v1
      kind: Release
      description: "Sample release controlled by Smith"
      metadata:
        name: release-v-1
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: k8s-deploy-test
            version: "1.0"
        template:
          metadata:
            labels:
              app: k8s-deploy-test
              version: "1.0"
          spec:
            containers:
            - name: tea
              image: nginxdemos/hello
              ports:
              - containerPort: 80
  - name: release-v-2
    spec:
      apiVersion: deploy.k8s/v1
      kind: Release
      description: "Sample release controlled by Smith"
      metadata:
        name: release-v-2
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: k8s-deploy-test
            version: "1.0"
        template:
          metadata:
            labels:
              app: k8s-deploy-test
              version: "1.0"
          spec:
            containers:
            - name: tea
              image: nginxdemos/hello
              ports:
              - containerPort: 80
  - name: release-v-3
    dependsOn:
      - release-v-2
    spec:
      apiVersion: deploy.k8s/v1
      kind: Release
      description: "Sample release controlled by Smith"
      metadata:
        name: release-v-3
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: k8s-deploy-test
            version: "1.0"
        template:
          metadata:
            labels:
              app: k8s-deploy-test
              version: "1.0"
          spec:
            containers:
            - name: tea
              image: nginxdemos/hello
              ports:
              - containerPort: 80
  - name: release-v-4
    dependsOn:
      - release-v-5
    spec:
      apiVersion: deploy.k8s/v1
      kind: Release
      description: "Sample release controlled by Smith"
      metadata:
        name: release-v-4
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: k8s-deploy-test
            version: "1.0"
        template:
          metadata:
            labels:
              app: k8s-deploy-test
              version: "1.0"
          spec:
            containers:
            - name: tea
              image: nginxdemos/hello
              ports:
              - containerPort: 80
  - name: release-v-5
    spec:
      apiVersion: deploy.k8s/v1
      kind: Release
      description: "Sample release controlled by Smith"
      metadata:
        name: release-v-5
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: k8s-deploy-test
            version: "1.0"
        template:
          metadata:
            labels:
              app: k8s-deploy-test
              version: "1.0"
          spec:
            containers:
            - name: tea
              image: nginxdemos/hello
              ports:
              - containerPort: 80                            