apiVersion: smith.atlassian.com/v1
kind: Bundle
metadata:
  name: release-smith-bundle-x
spec:
  resources:
  - Name: release-x-controlled-by-smith
    spec:
      apiVersion: deploy.k8s/v1
      kind: Release
      description: "Sample release controlled by Smith"
      metadata:
        name: release-smith-example-x
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: k8s-deploy-test
            version: "1.0"
        template:
          metadata:
            labels:
              app: k8s-deploy-test
              version: "1.0"
          spec:
            containers:
            - name: tea
              image: nginxdemos/hello
              ports:
              - containerPort: 80